title: handmade wares for the home
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.4371145803015679
  brandStrength: 0.5970084599684924
  rhythmicContrast: 0.2043162956833839
  brandColors:
    - '#DFD0CE'
    - '#C6B4A3'
    - '#382F39'
    - '#927F65'
    - '#6D536E'
  lightness: 0.05824458645656705
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: scout textiles
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7132617
layout_spectrum: 1
